--stngs.lua - default settings

-- This file is under a Creative Commons Attribution 4.0 International Licence
-- http://creativecommons.org/licenses/by/4.0/
-- You can mess around with it, mod it to your liking, and even redistribute it.
-- However, you must credit me.

ARCBank.Loaded = false
ARCBank.Settings = {}

--[[
 ____   ___    _   _  ___ _____   _____ ____ ___ _____   _____ _   _ _____   _    _   _   _      _____ ___ _     _____ _ 
|  _ \ / _ \  | \ | |/ _ \_   _| | ____|  _ \_ _|_   _| |_   _| | | | ____| | |  | | | | / \    |  ___|_ _| |   | ____| |
| | | | | | | |  \| | | | || |   |  _| | | | | |  | |     | | | |_| |  _|   | |  | | | |/ _ \   | |_   | || |   |  _| | |
| |_| | |_| | | |\  | |_| || |   | |___| |_| | |  | |     | | |  _  | |___  | |__| |_| / ___ \  |  _|  | || |___| |___|_|
|____/ \___/  |_| \_|\___/ |_|   |_____|____/___| |_|     |_| |_| |_|_____| |_____\___/_/   \_\ |_|   |___|_____|_____(_)

 ____   ___    _   _  ___ _____   _____ ____ ___ _____   _____ _   _ _____   _    _   _   _      _____ ___ _     _____ _ 
|  _ \ / _ \  | \ | |/ _ \_   _| | ____|  _ \_ _|_   _| |_   _| | | | ____| | |  | | | | / \    |  ___|_ _| |   | ____| |
| | | | | | | |  \| | | | || |   |  _| | | | | |  | |     | | | |_| |  _|   | |  | | | |/ _ \   | |_   | || |   |  _| | |
| |_| | |_| | | |\  | |_| || |   | |___| |_| | |  | |     | | |  _  | |___  | |__| |_| / ___ \  |  _|  | || |___| |___|_|
|____/ \___/  |_| \_|\___/ |_|   |_____|____/___| |_|     |_| |_| |_|_____| |_____\___/_/   \_\ |_|   |___|_____|_____(_)
                                                                                                                         

 ____   ___    _   _  ___ _____   _____ ____ ___ _____   _____ _   _ _____   _    _   _   _      _____ ___ _     _____ _ 
|  _ \ / _ \  | \ | |/ _ \_   _| | ____|  _ \_ _|_   _| |_   _| | | | ____| | |  | | | | / \    |  ___|_ _| |   | ____| |
| | | | | | | |  \| | | | || |   |  _| | | | | |  | |     | | | |_| |  _|   | |  | | | |/ _ \   | |_   | || |   |  _| | |
| |_| | |_| | | |\  | |_| || |   | |___| |_| | |  | |     | | |  _  | |___  | |__| |_| / ___ \  |  _|  | || |___| |___|_|
|____/ \___/  |_| \_|\___/ |_|   |_____|____/___| |_|     |_| |_| |_|_____| |_____\___/_/   \_\ |_|   |___|_____|_____(_)
                                                                                                                         
																														 
I have recieved too many questions regarding the "config file" or "The ATM is saying Contact an admin".

So, let me try to explain something to you...
																														 
DO NOT EDIT THIS FILE TO CHANGE THE CONFIG! READ THE README!
These are the default settings in order to prevent you from screwing it up!

arcbank help
^ GIVES YOU A FULL AND DETAILED DESCRIPTION OF ALL COMMANDS

arcbank settings_help (setting)
^ GIVES YOU A FULL DESCRIPTION OF ALL SETTINGS (Leave blank to show a list of all settings.)

arcbank settings (setting) (value)
^ SETS THE SETTING YOU WANT TO THE SPECIFIED VALUE.
]]
function ARCBank.SettingsReset() --DO NOT EDIT THIS!!!!
	--ARCBank.Settings[""]
	ARCBank.Settings["name"] = "ARCBank"
	ARCBank.Settings["name_long"] = "ARitz Cracker Bank"
	ARCBank.Settings["card_texture"] = "arc/atm_base/screen/card"
	ARCBank.Settings["card_weapon_slot"] = 1
	ARCBank.Settings["card_weapon_slotpos"] = 4
	ARCBank.Settings["atm_hack_time_rate"] = 1 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_hack_charge_rate"] = 1.5 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_hack_notify"] = {"TEAM_POLICE","TEAM_MAYOR","TEAM_CHIEF"} --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_hack_min_player"] = 3 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_hack_allowed_use"] = false
	ARCBank.Settings["atm_hack_allowed"] = {"TEAM_GANG","TEAM_MOB","TEAM_POLICE","TEAM_MAYOR","TEAM_CHIEF"}
	ARCBank.Settings["atm_hack_radar"] = true
	
	ARCBank.Settings["language"] = "en" --DO NOT EDIT THIS!!!!
	
	ARCBank.Settings["atm_holo"] = false --DO NOT EDIT THIS!!!!
	
	ARCBank.Settings["use_bank_for_payday"] = true --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_holo"] = true --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_holo_flicker"] = true --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_holo_rotate"] = true --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_holo_text"] = "$$ ATM $$"
	ARCBank.Settings["group_account_limit"] = 4 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["starting_cash"] = 500 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["perpetual_debt"] = false --DO NOT EDIT THIS!!!!
	ARCBank.Settings["autoban_time"] = 120 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["debt_limit"] = 10000  --DO NOT EDIT THIS!!!!
	
	ARCBank.Settings["interest_time"] = 24 --DO NOT EDIT THIS!!!!
	
	ARCBank.Settings["hack_max"] = 5000 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["hack_min"] = 25 --DO NOT EDIT THIS!!!!
	
	ARCBank.Settings["interest_enable"] = true
	
	ARCBank.Settings["standard_interest"] = 1 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["bronze_interest"] = 2 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["silver_interest"] = 4 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["gold_interest"] = 8 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["group_standard_interest"] = 2.5 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["group_premium_interest"] = 5 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["standard_requirement"] = {"user"} --DO NOT EDIT THIS!!!!
	ARCBank.Settings["bronze_requirement"] = {} --DO NOT EDIT THIS!!!!
	ARCBank.Settings["silver_requirement"] = {} --DO NOT EDIT THIS!!!!
	ARCBank.Settings["gold_requirement"] = {"admin"} --DO NOT EDIT THIS!!!!
	ARCBank.Settings["group_standard_requirement"] = {} --DO NOT EDIT THIS!!!!
	ARCBank.Settings["group_premium_requirement"] = {"admin"} --DO NOT EDIT THIS!!!!
	ARCBank.Settings["everything_requirement"] = {"operator","superadmin"} --DO NOT EDIT THIS!!!!
	ARCBank.Settings["notify_update"] = false --DO NOT EDIT THIS!!!!
	ARCBank.Settings["superadmin_only"] = false --DO NOT EDIT THIS!!!!
	ARCBank.Settings["owner_only"] = false --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_hack_min_hackerstoppers"] = 1 --DO NOT EDIT THIS!!!!
	ARCBank.Settings["atm_darkmode_default"] = false
	
end

ARCBank.SettingsReset()


